engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true

ratings:
   paths:
   - "**.js"
   - "**.css"

exclude_paths:
- "app/private/**"
- "app/css/geo-bootstrap/swatch/bootstrap.css"
- "data/datacreator.js"