language: node_js

node_js:
  - "0.10"

addons:
  code_climate:
    repo_token: 4c1b01eba7eeb3e9af53beaa4f097b5a49754c4edb8e95d59088bac519607637

after_script:
  cp "coverage/PhantomJS 1.9.7 (Linux)/lcov.info" coverage/lcov-client.info
  cp "coverage/server-tests/lcov.info" coverage/lcov-server.info
  ./node_modules/bin/lcov-result-merger 'coverage/lcov-*.info' 'coverage/lcov.info'
  dir coverage
  cat "./coverage/lcov.info" | ./node_modules/.bin/codeclimate