version: '{build}'
init:
  - git config --global core.autocrlf true
branches:
  except:
  - gh-pages
  - lightning-talk
environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 5
    - nodejs_version: 4
    - nodejs_version: 0.12
    - nodejs_version: 0.11
    - nodejs_version: 0.10
platform:
  - x64
install:
  - SET PATH=C:\Python27-x64;C:\Python27-x64\\Scripts;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install -g node-gyp
  - npm config set python python2.7
  - node --version && python --version
  - pip install lxml
  - npm install
  - grunt package-windows
build: off
test: off
matrix:
  fast_finish: true
artifacts:
  - path: dist\juice-shop-*_node4_win64.zip
deploy:
  - provider: GitHub
    auth_token:
      secure: bFkucwU1Zoh4EgzKmTAwONzQxuWPWrPGa+yXgadKQRd2jz5JPDZEw1f1vz2r+7i1
    on:
      branch: master
      appveyor_repo_tag: true
      platform: x64
      nodejs_version: 4
cache:
  - node_modules -> package.json
  - app\bower_components -> bower.json