version: '{build}'
init:
  - git config --global core.autocrlf true
branches:
  except:
  - gh-pages
  - lightning-talk
environment:
  matrix:
    - nodejs_version: 4 # recommended version
platform:
  - x64
install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version && npm --version
  - if exist node_modules rd /Q /S node_modules # workaround for npm install bug missing module dependencies
  - npm install
  - node_modules\.bin\grunt package --node=4 --platform=x64 --os=windows
build: off
test: off
matrix:
  fast_finish: true
artifacts:
  - path: dist\*
deploy:
  - provider: GitHub
    auth_token:
      secure: bFkucwU1Zoh4EgzKmTAwONzQxuWPWrPGa+yXgadKQRd2jz5JPDZEw1f1vz2r+7i1
    on:
      branch: master
      appveyor_repo_tag: true
